DROP database IF EXISTS dbElectrodomesticos;
CREATE DATABASE dbElectrodomesticos;
GO
USE dbElectrodomesticos;
GO

DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE(
 CODCLI CHAR (4) NOT NULL,
 NOMCLI varchar (60) NOT NULL,
 APECLI varchar (80)NOT NULL, 
 EMACLI varchar (80) NOT NULL ,
 CELCLI char (9) NOT NULL,
 DIRCLI varchar (70)NOT NULL,
 ESTCLI char(1)  NOT NULL
 CONSTRAINT CLIENTE_pk PRIMARY KEY  (CODCLI)
);
GO

DROP TABLE IF EXISTS VENDEDOR;
CREATE TABLE VENDEDOR(
 CODVEND char (4) NOT NULL,
 NOMVEND varchar (60) NOT NULL,
 APEVEND varchar (80)NOT NULL, 
 EMAVEND varchar (80) NOT NULL ,
 CELVEND char (9) NOT NULL,
 DIRVEND varchar (70)NOT NULL,
 ESTVEND char(1)  NOT NULL
 CONSTRAINT VENDEDOR_pk PRIMARY KEY  (CODVEND)
);
GO

DROP TABLE IF EXISTS PRODUCTO;
CREATE TABLE PRODUCTO(
 CODPRO char (5) NOT NULL,
 DESCPRO varchar (80) NOT NULL,
 CATPRO char (1) ,
 PREPRO decimal (8,2) ,
 STOCKPRO int,
 ESTPRO char(1)  NOT NULL
 CONSTRAINT PRODUCTO_pk PRIMARY KEY  (CODPRO)
);
GO

DROP TABLE IF EXISTS PROVEEDOR;
CREATE TABLE PROVEEDOR(
 CODPROV char (5) NOT NULL,
 RAZSOCPROV varchar (90) NOT NULL,
 RUCPROV char (11) NOT NULL,  --Cambio de Varchar a Char
 EMAPROV varchar (70) NOT NULL,
 ESTPROV char(1)  NOT NULL
 CONSTRAINT PROVEEDOR_pk PRIMARY KEY  (CODPROV)
);
GO

DROP TABLE IF EXISTS VENTA;
CREATE TABLE VENTA(
 CODVEN CHAR (5) NOT NULL,
 FECVEN datetime NOT NULL,
 CODCLI char(4)NOT NULL,
 CODVEND char (4) NOT NULL,
 ESTVEN char(1)  NOT NULL
 CONSTRAINT VENTA_pk PRIMARY KEY  (CODVEN)
);
GO

DROP TABLE IF EXISTS VENTADETALLE;
CREATE TABLE VENTADETALLE(
 IDVENDET int identity(1, 1),
 CODVEN char(5)NOT NULL,
 CODPRO char(5)NOT NULL,
 CANTPRO int
 CONSTRAINT VENTADETALLE_pk PRIMARY KEY  (IDVENDET)
);
GO

DROP TABLE IF EXISTS COMPRA;
CREATE TABLE COMPRA(
 CODCOM char (5),
 FECCOM datetime,
 CODPROV char (5),
 CODVEND char (4),
 ESTCOM char (1)
 CONSTRAINT COMPRA_pk PRIMARY KEY  (CODCOM)
);
GO

DROP TABLE IF EXISTS COMPRADETALLE;
CREATE TABLE COMPRADETALLE(
 IDCOMDET int,
 CODCOM char (5),
 CODPRO char (5),
 CANTPRO int
 CONSTRAINT COMPRADETALLE_pk PRIMARY KEY  (IDCOMDET)
);
GO



ALTER TABLE  VENTA
    ADD CONSTRAINT VENTA_CLIENTE FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI)
GO

ALTER TABLE VENTA
    ADD CONSTRAINT VENTA_VENDEDOR FOREIGN KEY (CODVEND) REFERENCES VENDEDOR (CODVEND)
GO

ALTER TABLE COMPRA
    ADD CONSTRAINT COMPRA_VENDEDOR FOREIGN KEY (CODVEND) REFERENCES VENDEDOR (CODVEND)
GO

ALTER TABLE COMPRA
    ADD CONSTRAINT COMPRA_PROVEEDOR FOREIGN KEY (CODPROV) REFERENCES PROVEEDOR (CODPROV)
GO

ALTER TABLE COMPRA
    ADD CONSTRAINT COMPRA_PROVEEDOR FOREIGN KEY (CODPROV) REFERENCES PROVEEDOR (CODPROV)
GO

ALTER TABLE VENTADETALLE
    ADD CONSTRAINT VENTADETALLE_PRODUCTO FOREIGN KEY (CODPRO) REFERENCES PRODUCTO (CODPRO)
GO

ALTER TABLE COMPRADETALLE
    ADD CONSTRAINT COMPRADETALLE_PRODUCTO FOREIGN KEY (CODPRO) REFERENCES PRODUCTO (CODPRO)
GO

ALTER TABLE VENTADETALLE
    ADD CONSTRAINT VENTADETALLE_VENTA FOREIGN KEY (CODVEN) REFERENCES VENTA (CODVEN)
GO

ALTER TABLE COMPRADETALLE
    ADD CONSTRAINT COMPRADETALLE_COMPRA FOREIGN KEY (CODCOM) REFERENCES COMPRA (CODCOM)
GO

CREATE Procedure CLIENTE_P
(
	@CODCLI CHAR (4),
	@NOMCLI varchar (60),
	@APECLI varchar (80),
	@EMACLI varchar (80),
	@CELCLI char (9),
	@DIRCLI varchar (70),
	@ESTCLI char(1)
)
as
begin
-------Inserci�n Stored Procedure CLIENTE -----
	insert into CLIENTE (CODCLI, NOMCLI, APECLI, EMACLI, CELCLI,DIRCLI,ESTCLI)
	values ('CL01', 'Juana', 'Campos Ort�z', 'juana.campos@gmail.com', '98748552', 'Av.Miraflores', 'A'),
('CL02', 'Sof�a', 'Barrios Salcedo', 'sofia.barrios@outlook.com', ' ', 'Jr.Huallga', 'A'),
('CL03','Claudio', 'P�rez Luna','claudio.perez@outlook.com','984512147','Av.�ibertadores', 'A'),
('CL04', 'Marcos', '�vila Manco', 'marcos.avila@yahoo.com', '','Calle Huallaga','A')
go

